### ISSUE TITLE
Error when pulumi up

### ISSUE THREAD

**Issue by MichaelPan1026** [bmpi-dev/code.bmpi.dev#1]
When I `pulumi up`, it’ll throw this error: 
```
error: Running program '/home/admin/vscode/code.bmpi.dev/server' failed with an unhandled exception:
    Error: ENOENT: no such file or directory, open '/home/admin/.ssh/id_rsa.pub'
        at Object.openSync (fs.js:462:3)
        at Object.readFileSync (fs.js:364:35)
        at Object.<anonymous> (/home/admin/vscode/code.bmpi.dev/server/index.ts:10:16)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Module.m._compile (/home/admin/vscode/code.bmpi.dev/server/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Object.require.extensions.<computed> [as .ts] (/home/admin/vscode/code.bmpi.dev/server/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)
```
I need help! Thanks!

**Comment by madawei2699** [comment]
It needs to have a default ssh key pair in local env.

**Comment by MichaelPan1026** [comment]
What’s the ENV name?

Dawei Ma ***@***.***>於 2021年9月9日 週四，04:47寫道：

**Comment by madawei2699** [comment]
You must creat SSH key pair and move it to ~/.ssh/ in your computer. See this doc: https://support.atlassian.com/bitbucket-cloud/docs/set-up-an-ssh-key/

**Comment by MichaelPan1026** [comment]
> 
> 
> You must creat SSH key pair and move it to ~/.ssh/ in your computer. See this doc: https://support.atlassian.com/bitbucket-cloud/docs/set-up-an-ssh-key/

Got it. But I'd tried to create SSH key pair before. And it kept throwing this: 
```
    error: Running program '/home/admin/vscode/code.bmpi.dev/server' failed with an unhandled exception:
    Error: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
        * Your query returned no results. Please change your search criteria and try again.


        at Object.callback (/home/admin/vscode/code.bmpi.dev/server/node_modules/@pulumi/pulumi/runtime/invoke.js:140:33)
        at Object.onReceiveStatus (/home/admin/vscode/code.bmpi.dev/server/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/admin/vscode/code.bmpi.dev/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/admin/vscode/code.bmpi.dev/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/admin/vscode/code.bmpi.dev/server/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
AWS Access Key ID and AWS Secret Key are correct.

**Comment by madawei2699** [comment]
It seems like your aws account cannot get AMI, you can search `ami-0cb5f8e033cfa84d2` in your aws web console(ec2), then post screenshot in here.
